Creating README.md with minor introductions
ghoshbishakh/freemex17 pull request #1
Opened 2017-04-01 14:41 UTC by AnirbanBanik1998

Added a readme.md file

2017-04-04 16:27 UTC, ghoshbishakh commented
@AnirbanBanik1998 please mention that the prerequisites are for building the app from the source code not playing the game. And please remove the "===============" from the last line

Thank!! 😄

2017-04-04 16:34 UTC, AnirbanBanik1998 commented
Oh I'm really sorry will try to improve upon this as soon as possible
On Apr 4, 2017 9:57 PM, "Bishakh Ghosh" <notifications@github.com> wrote:

> @AnirbanBanik1998 <https://github.com/AnirbanBanik1998> please mention
> that the prerequisites are for building the app from the source code not
> playing the game. And please remove the "===============" from the last line
>
> Thank!! 😄
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/lugnitdgp/freemex/pull/1#issuecomment-291555401>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AYv7sn1ukf7Cx57alXcxcuxr0PTce4vCks5rsm-GgaJpZM4Mwge6>
> .
>

2017-04-05 09:38 UTC, ghoshbishakh requested changes

2017-04-05 09:38 UTC, ghoshbishakh commented on README.md
> +--------------
Prequisites for building the source code not playing the game. So make a heading 'Building from source' and then put the subheading prerequisites

2017-04-05 09:38 UTC, ghoshbishakh commented on README.md
> +Freemex-In this project you have to contribute in building the app from the source code.
'Freemex-In this project you have to contribute in building the app from the source code. ' remove this line

2017-04-05 09:39 UTC, AnirbanBanik1998 commented
Made the changes

On Tue, Apr 4, 2017 at 10:04 PM, Anirban Banik <anirbanbanik17@gmail.com>
wrote:

> Oh I'm really sorry will try to improve upon this as soon as possible
> On Apr 4, 2017 9:57 PM, "Bishakh Ghosh" <notifications@github.com> wrote:
>
>> @AnirbanBanik1998 <https://github.com/AnirbanBanik1998> please mention
>> that the prerequisites are for building the app from the source code not
>> playing the game. And please remove the "===============" from the last line
>>
>> Thank!! 😄
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/lugnitdgp/freemex/pull/1#issuecomment-291555401>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe-auth/AYv7sn1ukf7Cx57alXcxcuxr0PTce4vCks5rsm-GgaJpZM4Mwge6>
>> .
>>
>

2017-04-05 09:48 UTC, ghoshbishakh approved these changes

2017-04-05 09:48 UTC, ghoshbishakh commented on README.md
> +                                 Building from source
Please see how markdown works. In github you can see a preview of the markdown file.
This is not proper syntax bringing int to the right by appending some spaces.

use single # for h1
use double ## for h2 .. like that.

See:
https://daringfireball.net/projects/markdown/syntax

2017-04-05 09:49 UTC, ghoshbishakh commented
Plsease do the fixes and I will merge. Thanks!

2017-04-07 04:45 UTC, ghoshbishakh commented
@AnirbanBanik1998 thanks!
But please check the preview yourself:
https://github.com/AnirbanBanik1998/freemex/blob/ba36f5a532e2cf075d41f0837e0b83cfefc2dc7b/README.md

Type the markdown in the github comments markdown editor and press preview and you will see.

'#'              -> creates a header

---------- '  -> also creates a header

So use any one of them

I prefre #

2017-04-07 05:00 UTC, AnirbanBanik1998 commented
I think now it is without much error.Sorry for taking so long

2017-04-07 05:00 UTC, merged

2017-04-07 05:00 UTC, ghoshbishakh commented
@AnirbanBanik1998 solid work!

2017-04-07 05:01 UTC, AnirbanBanik1998 commented
Thanks!