Balance
ghoshbishakh/freemex17 pull request #25
Opened 2019-03-11 18:15 UTC by godscreator

Fixes issue #23 - Created a transaction recording page "balance" with profit and loss column

branch name is "balance"

(p.s This is my first time contributing . )

2019-03-13 18:48 UTC, ankan17 requested changes
Thanks a lot for the PR. Looks just about right. However, there are a few minor modifications required.

2019-03-13 18:48 UTC, ankan17 commented on core/templates/core/balance.html
> +    			<th scope="col"> Qty.</th>
Just make it as "Quantity"

2019-03-13 18:48 UTC, ankan17 commented on core/templates/core/includes/navbar.html
> +                    <a class="nav-link" href="/balance">Balance</a>
I think it's better to name this feature (and hence, the tab) as "Transactions". Please change balance to transactions at all places.

2019-03-14 02:14 UTC, godscreator commented
Ok

On Thu, Mar 14, 2019, 12:18 AM Ankan Poddar <notifications@github.com wrote:

> *@ankan17* requested changes on this pull request.
>
> Thanks a lot for the PR. Looks just about right. However, there are a few
> minor modifications required.
> ------------------------------
>
> In core/templates/core/balance.html
> <https://github.com/lugnitdgp/freemex/pull/25#discussion_r265278624>:
>
> > +<!--Main layout-->
> +<div class="container balance">
> +    <br>
> +    <h1>Balance</h1>
> +    <hr>
> +    <h5>Cash in your hand: $<span id="playercash">{{ player.cash }}</span></h5>
> +    <br>
> +    <input type="text" id="market-search" onkeyup="marketSearch()" placeholder="Search for stock names..">
> +    <br><br>
> +
> +    <table class="table balance-sheet" >
> +    	<thead>
> +    		<tr>
> +    			<th scope="col"> Stock name</th>
> +    			<th scope="col"> Status</th>
> +    			<th scope="col"> Qty.</th>
>
> Just make it as "Quantity"
> ------------------------------
>
> In core/templates/core/includes/navbar.html
> <https://github.com/lugnitdgp/freemex/pull/25#discussion_r265279242>:
>
> > @@ -23,6 +23,9 @@
>                  <li class="nav-item {% if current == 'Market' %}active{% endif %}">
>                      <a class="nav-link" href="/market">Market</a>
>                  </li>
> +                <li class="nav-item {% if current == 'Balance' %}active{% endif %}">
> +                    <a class="nav-link" href="/balance">Balance</a>
>
> I think it's better to name this feature (and hence, the tab) as
> "Transactions". Please change balance to transactions at all places.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lugnitdgp/freemex/pull/25#pullrequestreview-214144907>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYLQWNK2fAKXOpIwNHSdYfIaaRKmafWmks5vWUgBgaJpZM4bpQQj>
> .
>

2019-03-14 07:38 UTC, godscreator commented
made changes as requested

2019-03-15 16:29 UTC, godscreator commented
Made changes as requested

On Thu, Mar 14, 2019, 7:43 AM Nitesh kumar <shubhamdragonsin@gmail.com
wrote:

> Ok
>
> On Thu, Mar 14, 2019, 12:18 AM Ankan Poddar <notifications@github.com
> wrote:
>
>> *@ankan17* requested changes on this pull request.
>>
>> Thanks a lot for the PR. Looks just about right. However, there are a few
>> minor modifications required.
>> ------------------------------
>>
>> In core/templates/core/balance.html
>> <https://github.com/lugnitdgp/freemex/pull/25#discussion_r265278624>:
>>
>> > +<!--Main layout-->
>> +<div class="container balance">
>> +    <br>
>> +    <h1>Balance</h1>
>> +    <hr>
>> +    <h5>Cash in your hand: $<span id="playercash">{{ player.cash }}</span></h5>
>> +    <br>
>> +    <input type="text" id="market-search" onkeyup="marketSearch()" placeholder="Search for stock names..">
>> +    <br><br>
>> +
>> +    <table class="table balance-sheet" >
>> +    	<thead>
>> +    		<tr>
>> +    			<th scope="col"> Stock name</th>
>> +    			<th scope="col"> Status</th>
>> +    			<th scope="col"> Qty.</th>
>>
>> Just make it as "Quantity"
>> ------------------------------
>>
>> In core/templates/core/includes/navbar.html
>> <https://github.com/lugnitdgp/freemex/pull/25#discussion_r265279242>:
>>
>> > @@ -23,6 +23,9 @@
>>                  <li class="nav-item {% if current == 'Market' %}active{% endif %}">
>>                      <a class="nav-link" href="/market">Market</a>
>>                  </li>
>> +                <li class="nav-item {% if current == 'Balance' %}active{% endif %}">
>> +                    <a class="nav-link" href="/balance">Balance</a>
>>
>> I think it's better to name this feature (and hence, the tab) as
>> "Transactions". Please change balance to transactions at all places.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/lugnitdgp/freemex/pull/25#pullrequestreview-214144907>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe-auth/AYLQWNK2fAKXOpIwNHSdYfIaaRKmafWmks5vWUgBgaJpZM4bpQQj>
>> .
>>
>

2019-03-15 16:32 UTC, ankan17 approved these changes

2019-03-15 16:34 UTC, merged

2019-03-15 16:37 UTC, godscreator commented
Thanks for merging 😁

On Fri, Mar 15, 2019, 10:02 PM Ankan Poddar <notifications@github.com wrote:

> *@ankan17* approved this pull request.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/lugnitdgp/freemex/pull/25#pullrequestreview-215133430>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AYLQWB-PJfh0D8pl2fZzIz-xH1ugSmM0ks5vW8sJgaJpZM4bpQQj>
> .
>